apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wafi-app
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: my-wafi-namespace
  project: default
  source:
    repoURL: 'https://github.com/odility/Gactions
    path: ./k8s-manifests
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
